server:
  port: 9000

spring:
  application:
    name: sujiakeji-eureka-server

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org.springframework.cloud: 'DEBUG'

management:
  endpoints:
    web:
      exposure:
        include: '*'
